name: Continuous Integration

on: [push]

jobs:
  build:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.2"]
        pythonVersion: ["2.7-dev", "3.5-dev", "3.6-dev", "3.7-dev", "3.8-dev", "3.9-dev"]
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Checkout recursively
        run: git submodule update --init --recursive

      - name: Create cache folder
        run: mkdir .cache

      - name: Cache Lua
        id: cache-lua
        uses: actions/cache@v2
        with:
          path: .cache/lua-${{ matrix.luaVersion }}
          key: ${{ runner.os }}-lua-${{ matrix.luaVersion }}-v2

      - name: Compile Lua
        if: steps.cache-lua.outputs.cache-hit != 'true'
        run: |
          cd .cache
          curl -R -O http://www.lua.org/ftp/lua-${{ matrix.luaVersion }}.tar.gz
          tar zxf lua-${{ matrix.luaVersion }}.tar.gz
          cd lua-${{ matrix.luaVersion }}
          sed 's/\(^CFLAGS.*\)/\1 -fPIC/' -i src/Makefile
          make linux

      - name: Install Lua
        run: |
          cd .cache/lua-${{ matrix.luaVersion }}
          sudo make install

      - name: Test Lua
        run: lua -v

      - name: Cache Pyenv
        id: cache-pyenv
        uses: actions/cache@v2
        with:
          path: .cache/pyenv
          key: ${{ runner.os }}-pyenv

      - name: Clone Pyenv
        if: steps.cache-pyenv.outputs.cache-hit != 'true'
        run: git clone https://github.com/pyenv/pyenv.git .cache/pyenv
        
      - name: Install Pyenv
        run: echo "$GITHUB_WORKSPACE/.cache/pyenv/bin" >> "$GITHUB_PATH"

      - name: Cache Python
        id: cache-python
        uses: actions/cache@v2
        with:
          path: $(pyenv root)/versions/${{ matrix.pythonVersion }}
          key: ${{ runner.os }}-python-${{ matrix.pythonVersion }}

      - name: Compile and install Python
        if: steps.cache-python.outputs.cache-hit != 'true'
        run: |
          eval "$(pyenv init -)"
          CONFIGURE_OPTS=--enable-shared pyenv install ${{ matrix.pythonVersion }}
          pyenv global ${{ matrix.pythonVersion }}

      - name: Test Python
        run: python --version

      - name: Install CMake
        run: sudo apt install cmake -y

      - name: Test CMake
        run: cmake --version

      - name: Configure build environment
        run: cmake -B build

      - name: Build Lupa and Lupafromlua
        run: cmake --build build

      - name: Test Lupafromlua
        run: lua tests/testbench.lua
