name: ci

on: [push]

jobs:
  build:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.2"]
        pythonVersion: ["2.7.18", "3.5.10", "3.6.12", "3.7.9", "3.8.7", "3.9.1"]
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: setup-lua
        env:
          luaVersion: ${{ matrix.luaVersion }}
        run: |
          curl -R -O http://www.lua.org/ftp/lua-${{ env.luaVersion }}.tar.gz
          tar zxf lua-${{ env.luaVersion }}.tar.gz
          cd lua-${{ env.luaVersion}}
          sed 's/\(^MYCFLAGS.*\)/\1 -fPIC/' -i src/Makefile
          sudo make linux install test
      - name: setup-python
        uses: gabrielfalcao/pyenv-action@v5
        env:
          pythonVersion: ${{ matrix.pythonVersion }}
        run: |
          CONFIGURE_OPTS=--enable-shared pyenv install ${{ env.pythonVersion }}
          pyenv global ${{ env.pythonVersion }}
          pip install -U pip
