name: Continuous Integration

on: [push]

jobs:
  build:
    strategy:
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.6", "5.4.2"]
        pythonVersion: ["2.7-dev", "3.5-dev", "3.6-dev", "3.7-dev", "3.8-dev", "3.9-dev"]
    
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Lua
        run: |
          curl -R -O http://www.lua.org/ftp/lua-${{ matrix.luaVersion }}.tar.gz
          tar zxf lua-${{ matrix.luaVersion }}.tar.gz
          cd lua-${{ matrix.luaVersion}}
          sed 's/\(^MYCFLAGS.*\)/\1 -fPIC/' -i src/Makefile
          sudo make linux install
      - name: Test Lua
        run: lua -v | grep -- ${{ matrix.luaVersion }}
      - name: Setup Pyenv
        run: |
          git clone https://github.com/pyenv/pyenv.git ~/.pyenv
          echo "${HOME}/.pyenv/bin" >> $GITHUB_PATH
      - name: Setup Python
        run: |
          eval "$(pyenv init -)"
          CONFIGURE_OPTS=--enable-shared pyenv install ${{ matrix.pythonVersion }}
          pyenv global ${{ matrix.pythonVersion }}
      - name: Test Python
        run: python -V | grep -- "$(echo ${{ matrix.pythonVersion }} | tr -cd [0-9.\n])"
